$StagingHost = "craveva-staging"
$StagingPath = "/var/www/craveva-staging/current/craveva"

Write-Host "Fixing permissions on $StagingHost..."

# 1. Fix ownership and permissions
# Ensure www-data owns storage and bootstrap/cache
$RemoteCommand = "sudo chown -R www-data:www-data $StagingPath/storage $StagingPath/bootstrap/cache"
# Ensure group write permission (775)
$RemoteCommand += " && sudo chmod -R 775 $StagingPath/storage $StagingPath/bootstrap/cache"

# 2. Clear cache as www-data to ensure new cache files are owned by www-data
# This prevents permission issues if cache was generated by root
$RemoteCommand += " && cd $StagingPath && sudo -u www-data php artisan optimize:clear"

Write-Host "Executing remote commands..."
ssh $StagingHost $RemoteCommand

Write-Host "Permissions fixed and cache cleared!"
