<?php

declare(strict_types=1);

use App\Enums\ProductType;
use App\Models\Product;
use Modules\Purchase\Services\ProductSkuGenerator;

it('generates sku with company prefix type code and sequence', function () {
    $companyId = (int) (company()->id ?? 1);
    $generator = app(ProductSkuGenerator::class);
    $sku = $generator->resolveForStore($companyId, ProductType::Goods->value, '');

    expect($sku)->toMatch('/^SP-FG-\d{6}$/');

    $sku2 = $generator->resolveForStore($companyId, ProductType::Goods->value, '');
    expect($sku2)->not->toBe($sku);
});

it('returns null sku for service products', function () {
    $companyId = (int) (company()->id ?? 1);
    $generator = app(ProductSkuGenerator::class);
    $sku = $generator->resolveForStore($companyId, ProductType::Service->value, '');

    expect($sku)->toBeNull();
});

it('keeps existing sku on update when field left empty', function () {
    $companyId = (int) (company()->id ?? 1);

    $product = Product::factory()->create([
        'company_id' => $companyId,
        'sku' => 'KEEP-'.uniqid('', true),
        'type' => ProductType::Goods->value,
    ]);

    $generator = app(ProductSkuGenerator::class);
    $sku = $generator->resolveForUpdate($product, ProductType::Goods->value, '');

    expect($sku)->toBe($product->sku);
});

it('treats auto-generated placeholder as empty on store', function () {
    $generator = app(ProductSkuGenerator::class);

    expect($generator->shouldAutoGenerate(ProductType::Goods->value, __('purchase::app.skuAutoGeneratedPlaceholder')))
        ->toBeTrue();
});
