<?php

declare(strict_types=1);

namespace Modules\Purchase\Services;

use App\Enums\ProductType;
use App\Models\Product;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class ProductSkuGenerator
{
    private const SEQ_WIDTH = 6;

    /**
     * @return array<string, string>
     */
    private const TYPE_SCOPE_CODES = [
        ProductType::Goods->value => 'FG',
        ProductType::RawMaterial->value => 'RM',
        ProductType::SemiFinished->value => 'SFG',
        ProductType::Packaging->value => 'PKG',
    ];

    public function shouldAutoGenerate(?string $type, ?string $sku): bool
    {
        if (ProductType::isService($type)) {
            return false;
        }

        return $this->isBlankOrAutoPlaceholder($sku);
    }

    public function isBlankOrAutoPlaceholder(?string $sku): bool
    {
        $trimmed = trim((string) $sku);

        if ($trimmed === '') {
            return true;
        }

        $placeholders = [
            strtolower(__('purchase::app.skuAutoGeneratedPlaceholder')),
            'auto-generated',
            'tự động',
        ];

        return in_array(strtolower($trimmed), $placeholders, true);
    }

    public function generate(int $companyId, string $type): string
    {
        $scopeKey = self::TYPE_SCOPE_CODES[$type] ?? 'FG';
        $prefix = $this->companyPrefix($companyId);
        $next = $this->nextSequenceValue($companyId, $scopeKey);

        return sprintf('%s-%s-%0'.self::SEQ_WIDTH.'d', $prefix, $scopeKey, $next);
    }

    public function resolveForStore(int $companyId, string $type, ?string $requestedSku): ?string
    {
        if (ProductType::isService($type)) {
            return null;
        }

        if ($this->shouldAutoGenerate($type, $requestedSku)) {
            return $this->generateUnique($companyId, $type);
        }

        return trim((string) $requestedSku);
    }

    public function resolveForUpdate(Product $product, string $type, ?string $requestedSku): ?string
    {
        if (ProductType::isService($type)) {
            return null;
        }

        if ($this->isBlankOrAutoPlaceholder($requestedSku)) {
            $existing = trim((string) ($product->sku ?? ''));

            return $existing !== '' ? $existing : $this->generateUnique((int) $product->company_id, $type);
        }

        return trim((string) $requestedSku);
    }

    protected function generateUnique(int $companyId, string $type): string
    {
        for ($attempt = 0; $attempt < 5; $attempt++) {
            $candidate = $this->generate($companyId, $type);
            $exists = Product::withoutGlobalScopes()
                ->where('company_id', $companyId)
                ->where('sku', $candidate)
                ->exists();

            if (! $exists) {
                return $candidate;
            }
        }

        return $this->generate($companyId, $type).'-'.Str::upper(Str::random(4));
    }

    protected function companyPrefix(int $companyId): string
    {
        $configured = config('purchase.product_sku_prefix');

        if (is_string($configured) && $configured !== '') {
            $prefix = Str::upper(preg_replace('/[^A-Z0-9]/', '', $configured) ?? '');

            if ($prefix !== '') {
                return substr($prefix, 0, 8);
            }
        }

        return 'SP';
    }

    protected function nextSequenceValue(int $companyId, string $scopeKey): int
    {
        if (! Schema::hasTable('product_sku_sequences')) {
            return $this->fallbackMaxFromProducts($companyId, $scopeKey) + 1;
        }

        return (int) DB::transaction(function () use ($companyId, $scopeKey): int {
            $row = DB::table('product_sku_sequences')
                ->where('company_id', $companyId)
                ->where('scope_key', $scopeKey)
                ->lockForUpdate()
                ->first();

            if ($row === null) {
                $start = $this->fallbackMaxFromProducts($companyId, $scopeKey);
                DB::table('product_sku_sequences')->insert([
                    'company_id' => $companyId,
                    'scope_key' => $scopeKey,
                    'last_value' => $start + 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);

                return $start + 1;
            }

            $next = (int) $row->last_value + 1;
            DB::table('product_sku_sequences')
                ->where('id', $row->id)
                ->update([
                    'last_value' => $next,
                    'updated_at' => now(),
                ]);

            return $next;
        });
    }

    protected function fallbackMaxFromProducts(int $companyId, string $scopeKey): int
    {
        $prefix = $this->companyPrefix($companyId);
        $pattern = $prefix.'-'.$scopeKey.'-%';
        $max = 0;

        $skus = Product::withoutGlobalScopes()
            ->where('company_id', $companyId)
            ->where('sku', 'like', $pattern)
            ->pluck('sku');

        foreach ($skus as $sku) {
            if (preg_match('/-(\d+)$/', (string) $sku, $matches) === 1) {
                $max = max($max, (int) $matches[1]);
            }
        }

        return $max;
    }
}
