<?php

declare(strict_types=1);

/**
 * Sync productFormInvalidData into all Purchase LanguagePack app.php locales.
 * Run: php scripts/patch_purchase_product_form_invalid_data_lang.php
 */
$en = include __DIR__.'/../Modules/LanguagePack/Languages/modules/Purchase/en/app.php';
$vi = include __DIR__.'/../Modules/LanguagePack/Languages/modules/Purchase/vi/app.php';

$defaults = [
    'en' => $en['productFormInvalidData'] ?? 'Invalid data',
    'vi' => $vi['productFormInvalidData'] ?? 'Dữ liệu không hợp lệ',
];

$dir = __DIR__.'/../Modules/LanguagePack/Languages/modules/Purchase';
$patched = 0;

foreach (glob($dir.'/*/app.php') ?: [] as $file) {
    $data = include $file;
    if (! is_array($data) || isset($data['productFormInvalidData']) || ! isset($data['sku'])) {
        continue;
    }

    $locale = basename(dirname($file));
    $value = $defaults[$locale] ?? $defaults['en'];

    $out = [];
    foreach ($data as $key => $val) {
        $out[$key] = $val;
        if ($key === 'skuAutoGeneratedPlaceholder' || ($key === 'sku' && ! isset($data['skuAutoGeneratedPlaceholder']))) {
            $out['productFormInvalidData'] = $value;
        }
    }

    if (! isset($out['productFormInvalidData'])) {
        $out['productFormInvalidData'] = $value;
    }

    file_put_contents($file, "<?php\n\nreturn ".var_export($out, true).";\n");
    echo "patched: {$file}\n";
    $patched++;
}

echo "Done. Patched {$patched} LanguagePack locale file(s).\n";
