<?php

declare(strict_types=1);

$en = include __DIR__.'/../Modules/LanguagePack/Languages/modules/Purchase/en/app.php';
$value = $en['skuAutoGeneratedPlaceholder'] ?? 'Auto-generated';
$dir = __DIR__.'/../Modules/LanguagePack/Languages/modules/Purchase';
$patched = 0;

foreach (glob($dir.'/*/app.php') ?: [] as $file) {
    if (
        str_contains($file, DIRECTORY_SEPARATOR.'en'.DIRECTORY_SEPARATOR)
        || str_contains($file, DIRECTORY_SEPARATOR.'vi'.DIRECTORY_SEPARATOR)
    ) {
        continue;
    }

    $data = include $file;
    if (! is_array($data) || isset($data['skuAutoGeneratedPlaceholder']) || ! isset($data['sku'])) {
        continue;
    }

    $out = [];
    foreach ($data as $key => $val) {
        $out[$key] = $val;
        if ($key === 'sku') {
            $out['skuAutoGeneratedPlaceholder'] = $value;
        }
    }

    file_put_contents($file, "<?php\n\nreturn ".var_export($out, true).";\n");
    $patched++;
}

echo "Patched {$patched} files.\n";
