<?php

declare(strict_types=1);

/**
 * Insert P2-UOM keys into all Purchase LanguagePack app.php locales (except en/vi).
 * Run: php scripts/patch_purchase_uom_lang_keys.php
 */
$en = include __DIR__.'/../Modules/LanguagePack/Languages/modules/Purchase/en/app.php';

$keys = [
    'skuAutoGeneratedPlaceholder',
    'productFormSectionUnits',
    'productUnitConversionsHelp',
    'productUnitColumnUnit',
    'productUnitColumnFactor',
    'productUnitColumnForSale',
    'productUnitAddRow',
    'productUnitAddRowHint',
    'productUnitCustomPrice',
    'productUnitQuantityBaseHint',
];

$block = [];
foreach ($keys as $key) {
    $block[$key] = $en[$key];
}

$dir = __DIR__.'/../Modules/LanguagePack/Languages/modules/Purchase';
$patched = 0;

foreach (glob($dir.'/*/app.php') ?: [] as $file) {
    if (
        str_contains($file, DIRECTORY_SEPARATOR.'en'.DIRECTORY_SEPARATOR)
        || str_contains($file, DIRECTORY_SEPARATOR.'vi'.DIRECTORY_SEPARATOR)
    ) {
        continue;
    }

    $data = include $file;
    if (! is_array($data) || isset($data['productFormSectionUnits'])) {
        continue;
    }

    $anchor = null;
    if (isset($data['productFormSectionPricing'])) {
        $anchor = 'productFormSectionPricing';
    } elseif (isset($data['salesInformation'])) {
        $anchor = 'salesInformation';
    } elseif (isset($data['sellingPrice'])) {
        $anchor = 'sellingPrice';
    }

    if ($anchor === null) {
        continue;
    }

    $out = [];
    foreach ($data as $key => $value) {
        $out[$key] = $value;
        if ($key === $anchor) {
            foreach ($block as $bk => $bv) {
                $out[$bk] = $bv;
            }
        }
    }

    $content = "<?php\n\nreturn ".var_export($out, true).";\n";
    file_put_contents($file, $content);
    echo "patched: {$file}\n";
    $patched++;
}

echo "Done. Patched {$patched} locale file(s).\n";
