@php
    use App\Enums\ProductType;

    $hasProduct = isset($product) && $product;
    $currencyCode = company()->currency->currency_code;
    $trackInventoryDisabled = isset($trackInventory) && $trackInventory === 'disable';
    $serviceType = $hasProduct && $product->type === 'service';
    $selectedProductType = old('type', $hasProduct && filled($product?->type) ? $product->type : ProductType::Goods->value);
    $hideSellingPrice = ProductType::hidesSellingPriceOnPurchaseForm($selectedProductType);
    $hideCostPrice = ProductType::hidesCostPriceOnPurchaseForm($selectedProductType);
    $showCustomCheckbox = ProductType::supportsCostFromBomOnPurchaseForm($selectedProductType);
    $costFromBomChecked = (bool) old('cost_from_bom', $hasProduct ? $product->cost_from_bom : false);
    $costPriceDisabled = $showCustomCheckbox && $costFromBomChecked;
    $hideB2bExtraPricing = ProductType::hidesB2bExtraPricingOnPurchaseForm($selectedProductType);
    $useOptionalPricingTaxAccordion = ProductType::usesTaxSectionAccordionOnPurchaseForm($selectedProductType);
    $hideClientPurchase = ProductType::hidesClientPurchaseToggleOnPurchaseForm($selectedProductType);
    $hideInventoryMetadata = ProductType::hidesInventoryMetadataOnPurchaseForm($selectedProductType);
    $hideInventorySection = ProductType::hidesInventorySectionOnPurchaseForm($selectedProductType);
    $hideUnitType = ProductType::hidesUnitTypeOnPurchaseForm($selectedProductType);
    $hideDescriptionAttributes = ProductType::hidesDescriptionAttributesOnPurchaseForm($selectedProductType);
    $showCostPriceColumn = ProductType::showsCostPriceOnPurchaseForm($selectedProductType);
    $showTrackInventory = $hasProduct ? !$serviceType : true;
    $trackInventoryChecked = $hasProduct && (int) $product->track_inventory === 1;
    $showOpeningStock = $hasProduct ? !$serviceType && $trackInventoryChecked : false;
    $warehouseStockUi = in_array('warehouse', user_modules() ?: [], true) || in_array('production', user_modules() ?: [], true);
    $activeWarehouseCount = 0;
    if (class_exists(\Modules\Warehouse\Entities\Warehouse::class) && \Illuminate\Support\Facades\Schema::hasTable('warehouses')) {
        $activeWarehouseCount = \Modules\Warehouse\Entities\Warehouse::where('company_id', company()->id)->where('status', 'active')->count();
    }
    $openingStockFieldHelp = __('purchase::app.openingStockFieldHelp');
    if ($warehouseStockUi) {
        $openingStockFieldHelp .= ' ' . __('purchase::app.openingStockFieldHelpExtended');
    }
@endphp

{{-- 1. Identity --}}
<div class="col-12 purchase-product-form-section">
    @include('purchase::purchase-products.partials.product-form-section-heading', ['title' => __('purchase::app.productFormSectionIdentity')])
    <div class="row">
        <div class="col-lg-4 col-md-6">
            @include('purchase::partials.product-type-select', ['product' => $product ?? null])
        </div>
        <div class="col-lg-4 col-md-6">
            <x-forms.text fieldId="name" :fieldLabel="__('app.name')" fieldName="name" fieldRequired="true" :fieldPlaceholder="__('placeholders.productName')" :fieldValue="$hasProduct ? $product->name : ''">
            </x-forms.text>
        </div>
        <div class="col-lg-4 col-md-6" id="sku_id">
            <x-forms.text fieldId="sku" :fieldLabel="__('purchase::app.sku')" fieldName="sku" :fieldRequired="$hasProduct && !$serviceType" :fieldPlaceholder="__('purchase::app.skuAutoGeneratedPlaceholder')" :fieldValue="$hasProduct ? $product->sku : ''">
            </x-forms.text>
        </div>
    </div>
</div>

{{-- 2. Classification --}}
<div class="col-12 purchase-product-form-section">
    @include('purchase::purchase-products.partials.product-form-section-heading', ['title' => __('purchase::app.productFormSectionClassification')])
    <div class="row">
        <div class="col-lg-4 col-md-6 product-unit-type-field @if ($hideUnitType) d-none @endif">
            <div class="form-group my-3">
                <x-forms.label fieldId="unit_type_id" :fieldLabel="__('modules.unitType.unitType')">
                </x-forms.label>
                <x-forms.input-group>
                    <select class="form-control unit_type select-picker" name="unit_type" id="unit_type_id" data-live-search="true">
                        @foreach ($unit_types as $unit_type)
                            <option value="{{ $unit_type->id }}" @if ($hasProduct && $unit_type->id == $product->unit_id) selected @elseif (!$hasProduct && $unit_type->default == 1) selected @endif>{{ ucwords($unit_type->unit_type) }}
                            </option>
                        @endforeach
                    </select>
                    @if (user()->permission('manage_finance_setting') == 'all')
                        <x-slot name="append">
                            <button id="add-unit-type" type="button" data-toggle="tooltip" data-original-title="{{ __('app.add') . ' ' . __('modules.unitType.unitType') }}" class="btn btn-outline-secondary border-grey">@lang('app.add')</button>
                        </x-slot>
                    @endif
                </x-forms.input-group>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="form-group my-3">
                <x-forms.label fieldId="product_category_id" :fieldLabel="__('modules.productCategory.productCategory')">
                </x-forms.label>
                <x-forms.input-group>
                    <select class="form-control select-picker" name="category_id" id="product_category_id" data-live-search="true">
                        <option value="">--</option>
                        @foreach ($categories as $category)
                            <option value="{{ $category->id }}" @if ($hasProduct && $category->id == $product->category_id) selected @endif>
                                {{ mb_ucwords($category->category_name) }}</option>
                        @endforeach
                    </select>
                    @if ($addProductCategoryPermission == 'all' || $addProductCategoryPermission == 'added')
                        <x-slot name="append">
                            <button id="add-category" type="button" data-toggle="tooltip" data-original-title="{{ __('app.add') . ' ' . __('modules.productCategory.productCategory') }}" class="btn btn-outline-secondary border-grey">@lang('app.add')</button>
                        </x-slot>
                    @endif
                </x-forms.input-group>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="form-group my-3">
                <x-forms.label fieldId="sub_category_id" :fieldLabel="__('modules.productCategory.productSubCategory')">
                </x-forms.label>
                <x-forms.input-group>
                    <select class="form-control select-picker" name="sub_category_id" id="sub_category_id" data-live-search="true">
                        @if ($hasProduct && $product->category_id)
                            <option value="">@lang('messages.noProductSubCategoryAdded')</option>
                            @foreach ($subCategories as $subCategory)
                                <option value="{{ $subCategory->id }}" @if ($subCategory->id == $product->sub_category_id) selected @endif>
                                    {{ mb_ucwords($subCategory->category_name) }}</option>
                            @endforeach
                        @else
                            <option value="">@lang('messages.noProductSubCategoryAdded')</option>
                            @foreach ($subCategories as $subCategory)
                                <option value="{{ $subCategory->id }}">{{ mb_ucwords($subCategory->category_name) }}</option>
                            @endforeach
                        @endif
                    </select>
                    @if ($addProductSubCategoryPermission == 'all' || $addProductSubCategoryPermission == 'added')
                        <x-slot name="append">
                            <button id="add-sub-category" type="button" data-toggle="tooltip" data-original-title="{{ __('app.add') . ' ' . __('modules.productCategory.productSubCategory') }}" class="btn btn-outline-secondary border-grey">@lang('app.add')</button>
                        </x-slot>
                    @endif
                </x-forms.input-group>
            </div>
        </div>
    </div>
</div>

{{-- 3. Pricing --}}
<div class="col-12 purchase-product-form-section">
    @include('purchase::purchase-products.partials.product-form-section-heading', ['title' => __('purchase::app.productFormSectionPricing')])
    <div class="row">
        @if ($showCustomCheckbox)
            <div class="col-12 product-cost-from-bom-toggle">
                <div class="form-group my-3 mb-2">
                    <x-forms.checkbox :fieldLabel="__('purchase::app.productCustomCostFromBom')" fieldName="cost_from_bom" fieldId="cost_from_bom" fieldValue="1" :checked="$costFromBomChecked" />
                    <p class="text-dark-grey f-12 mb-0 mt-1">@lang('purchase::app.productCustomCostFromBomHelp')</p>
                </div>
            </div>
        @endif
        <div class="col-lg-3 col-md-6 product-selling-price-column @if ($hideSellingPrice) d-none @endif">
            <div class="form-group my-3">
                <label class="f-14 text-dark-grey mb-12" for="selling_price">@lang('purchase::app.sellingPrice')<sup class="text-red f-14 mr-1 product-selling-price-required">*</sup></label>
                <div class="input-group">
                    <div class="input-group-prepend height-35">
                        <span class="input-group-text border-grey f-15 bg-additional-grey px-3 text-dark">{{ $currencyCode }}</span>
                    </div>
                    <input type="number" name="selling_price" id="selling_price" class="form-control height-35 f-15 readonly-background" value="{{ $hasProduct && $product->price ? $product->price : '' }}" placeholder="0" min="0">
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 product-cost-price-column @if (!$showCostPriceColumn) d-none @endif">
            <div class="form-group my-3 product-cost-price-field">
                <label class="f-14 text-dark-grey mb-12" for="purchase_price">@lang('purchase::app.costPrice')<sup class="text-red f-14 mr-1 product-cost-price-required @if ($costPriceDisabled) d-none @endif">*</sup></label>
                <div class="input-group">
                    <div class="input-group-prepend height-35">
                        <span class="input-group-text border-grey f-15 bg-additional-grey px-3 text-dark">{{ $currencyCode }}</span>
                    </div>
                    <input type="number" name="purchase_price" id="purchase_price" class="form-control height-35 f-15 readonly-background @if ($costPriceDisabled) disabled-background @endif" value="{{ $hasProduct && $product->purchase_price !== null && $product->purchase_price !== '' ? $product->purchase_price : '' }}" placeholder="0" min="0" step="any"
                        @if ($costPriceDisabled) disabled @endif>
                </div>
                @if ($hideSellingPrice)
                    <p class="text-dark-grey f-12 mb-0 mt-1">@lang('purchase::app.productFormCostOnlyHelp')</p>
                @endif
                @if ($costPriceDisabled)
                    <p class="text-warning f-12 mb-0 mt-1 product-cost-from-bom-pending-hint">@lang('purchase::app.productCustomCostFromBomPending')</p>
                @endif
            </div>
        </div>
        @if ($useOptionalPricingTaxAccordion)
            <div class="col-12 product-optional-pricing-tax-block">
                <p class="product-optional-pricing-tax-toggle mb-0">
                    <a class="f-14 font-weight-bold text-dark-grey text-capitalize purchase-form-collapse-toggle collapsed d-block pb-2 mb-3 border-bottom-grey" data-toggle="collapse" href="#productOptionalPricingTaxCollapse" role="button" aria-expanded="false" aria-controls="productOptionalPricingTaxCollapse">
                        @lang('purchase::app.productFormOptionalPricingTax')
                        <i class="fa fa-chevron-down ml-1"></i>
                    </a>
                </p>
                <div id="productOptionalPricingTaxCollapse" class="collapse product-optional-pricing-tax-fields">
                    <div class="product-b2b-extra-pricing-fields @if ($hideB2bExtraPricing) d-none @endif">
                        <div class="row">
                            <div class="col-lg-3 col-md-6">
                                <x-forms.number fieldId="wholesale_price" :fieldLabel="__('Wholesale_Price.Wholesale Price')" fieldName="wholesale_price" :fieldPlaceholder="__('0')" :fieldValue="$hasProduct ? $product->wholesale_price : ''">
                                </x-forms.number>
                            </div>
                            <div class="col-lg-3 col-md-6">
                                <x-forms.number fieldId="price_per_box" :fieldLabel="__('Price_Per_Box.Price Per Box')" fieldName="price_per_box" :fieldPlaceholder="__('0')" :fieldValue="$hasProduct ? $product->price_per_box : ''">
                                </x-forms.number>
                            </div>
                            <div class="col-lg-3 col-md-6">
                                <x-forms.number fieldId="employee_price" :fieldLabel="__('Employee_Price.Employee Price')" fieldName="employee_price" :fieldPlaceholder="__('0')" :fieldValue="$hasProduct ? $product->employee_price : ''">
                                </x-forms.number>
                            </div>
                        </div>
                        <hr class="my-3 product-optional-pricing-tax-divider @if ($hideB2bExtraPricing) d-none @endif">
                    </div>
                    <div class="row product-optional-tax-fields">
                        <div class="col-lg-4 col-md-6">
                            <div class="form-group my-3">
                                <x-forms.label fieldId="tax_id" :fieldLabel="__('modules.invoices.tax')">
                                </x-forms.label>
                                <x-forms.input-group>
                                    <select class="form-control tax select-picker" name="tax[]" id="tax_id" data-live-search="true" multiple="true">
                                        @foreach ($taxes as $tax)
                                            <option value="{{ $tax->id }}" @if ($hasProduct && isset($product->taxes) && array_search($tax->id, json_decode($product->taxes) ?: [], true) !== false) selected @endif>{{ strtoupper($tax->tax_name) }}:
                                                {{ $tax->rate_percent }}%
                                            </option>
                                        @endforeach
                                    </select>
                                    @if (user()->permission('manage_tax') == 'all')
                                        <x-slot name="append">
                                            <button id="add-tax" type="button" data-toggle="tooltip" data-original-title="{{ __('app.add') . ' ' . __('modules.invoices.tax') }}" class="btn btn-outline-secondary border-grey">@lang('app.add')</button>
                                        </x-slot>
                                    @endif
                                </x-forms.input-group>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <x-forms.text fieldId="hsn_sac_code" :fieldLabel="__('app.hsnSac')" fieldName="hsn_sac_code" :fieldPlaceholder="__('placeholders.hsnSac')" :fieldValue="$hasProduct ? $product->hsn_sac_code : ''">
                            </x-forms.text>
                        </div>
                        <div class="col-lg-4 col-md-6 product-client-purchase-toggle @if ($hideClientPurchase) d-none @endif">
                            <div class="form-group my-3">
                                <x-forms.checkbox class="mr-0" :fieldLabel="__('app.clientPurchase')" fieldName="purchase_allow" fieldId="purchase_allow" fieldValue="no" fieldRequired="true" :checked="$hasProduct && $product->allow_purchase == 1" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
</div>

@include('purchase::purchase-products.partials.product-unit-conversions')
@include('purchase::purchase-products.partials.product-type-dependent-fields')

{{-- 5. Inventory & shelf life --}}
<div class="col-12 purchase-product-form-section product-inventory-section @if ($hideInventorySection) d-none @endif">
    @include('purchase::purchase-products.partials.product-form-section-heading', ['title' => __('purchase::app.productFormSectionInventory')])
    <div class="row">
        <div class="col-12 {{ $showTrackInventory ? '' : 'd-none' }} track_inventory_div">
            <div class="form-group my-3 mb-2">
                @if ($trackInventoryDisabled)
                    <x-forms.checkbox class="mr-0" :fieldLabel="__('purchase::app.trackInventory')" fieldName="track_inventory" fieldId="track_inventory" fieldValue="1" fieldRequired="true" :checked="$trackInventoryChecked" disabled />
                @else
                    <x-forms.checkbox class="mr-0" :fieldLabel="__('purchase::app.trackInventory')" fieldName="track_inventory" fieldId="track_inventory" fieldValue="1" fieldRequired="true" :checked="$trackInventoryChecked" />
                @endif
                <label class="track_inventory_label text-dark-grey f-13 d-block mt-2" id="track_inventory_label">@lang('purchase::messages.trackInventoryMsg')</label>
            </div>
        </div>
        <div class="col-12 track_inventory {{ $showOpeningStock ? '' : 'd-none' }}">
            @if ($warehouseStockUi && $activeWarehouseCount === 0)
                <div class="alert alert-warning mb-3" role="alert">
                    @lang('purchase::app.openingStockNoWarehouseAlert')
                    @if (Route::has('warehouse.index') && in_array('warehouse', user_modules() ?: [], true))
                        <a href="{{ route('warehouse.index') }}" class="alert-link">@lang('warehouse::app.warehouses')</a>
                    @endif
                </div>
            @endif
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    @if ($hasProduct && $trackInventoryChecked && $trackInventoryDisabled)
                        <x-forms.text fieldId="opening_stock" fieldRequired="true" fieldReadOnly="true" :fieldLabel="__('purchase::app.openingStock')" fieldName="opening_stock" :fieldPlaceholder="__('purchase::placeholders.openingStock')" :fieldValue="$product->quantityInventory->net_quantity ?? ''" :popover="__('purchase::app.openingStockPopoverHelp')" :fieldHelp="$openingStockFieldHelp">
                        </x-forms.text>
                    @else
                        <x-forms.number fieldId="opening_stock" fieldRequired="true" :fieldLabel="__('purchase::app.openingStock')" fieldName="opening_stock" :fieldPlaceholder="__('purchase::placeholders.openingStock')" :fieldValue="$hasProduct ? $product->opening_stock : ''" :popover="__('purchase::app.openingStockPopoverHelp')" :fieldHelp="$openingStockFieldHelp">
                        </x-forms.number>
                    @endif
                </div>
                <div class="col-lg-4 col-md-6 product-inventory-metadata @if ($hideInventoryMetadata) d-none @endif">
                    <x-forms.select fieldId="storage_condition" :fieldLabel="__('Storage_Condition.Storage Condition')" fieldName="storage_condition" search="true">
                        <option value="">--</option>
                        <option value="Frozen" @if ($hasProduct && $product->storage_condition == 'Frozen') selected @endif>Frozen</option>
                        <option value="Chilled" @if ($hasProduct && $product->storage_condition == 'Chilled') selected @endif>Chilled</option>
                        <option value="Ambient" @if ($hasProduct && $product->storage_condition == 'Ambient') selected @endif>Ambient</option>
                    </x-forms.select>
                </div>
                <div class="col-lg-4 col-md-6 product-inventory-metadata @if ($hideInventoryMetadata) d-none @endif">
                    <x-forms.text fieldId="certification" :fieldLabel="__('Certification.Certification')" fieldName="certification" :fieldPlaceholder="__('Certification.Certification')" :fieldValue="$hasProduct ? $product->certification : ''">
                    </x-forms.text>
                </div>
                <div class="col-lg-4 col-md-6 product-inventory-metadata @if ($hideInventoryMetadata) d-none @endif">
                    <x-forms.text fieldId="inventory_type" :fieldLabel="__('Inventory_Type.Inventory Type')" fieldName="inventory_type" :fieldPlaceholder="__('Inventory_Type.Inventory Type')" :fieldValue="$hasProduct ? $product->inventory_type : ''">
                    </x-forms.text>
                </div>
                <div class="col-lg-4 col-md-6 product-inventory-metadata @if ($hideInventoryMetadata) d-none @endif">
                    <x-forms.number fieldId="shelf_life_days" :fieldLabel="__('app.shelfLifeDays')" fieldName="shelf_life_days" :fieldPlaceholder="__('app.shelfLifeDays')" :fieldValue="$hasProduct ? $product->shelf_life_days ?? '' : ''" minValue="0">
                    </x-forms.number>
                </div>
                <div class="col-lg-4 col-md-6 product-inventory-metadata @if ($hideInventoryMetadata) d-none @endif">
                    <x-forms.datepicker fieldId="expiry_date" :fieldLabel="__('app.expiryDate')" fieldName="expiry_date" :fieldPlaceholder="__('placeholders.date')" :fieldValue="$hasProduct && $product->expiry_date ? $product->expiry_date->timezone(company()->timezone)->format(company()->date_format) : ''" />
                </div>
            </div>
        </div>
    </div>
</div>

{{-- 6. Description & attributes (optional accordion) --}}
<div class="col-12 purchase-product-form-section product-description-section">
    @include('purchase::purchase-products.partials.product-form-accordion-heading', [
        'title' => __('purchase::app.productFormSectionDetailsOptional'),
        'targetId' => 'productDescriptionCollapse',
        'wrapperClass' => 'product-description-accordion-toggle',
    ])
    <div id="productDescriptionCollapse" class="collapse product-description-fields">
        <div class="row">
            <div class="col-12">
                <div class="form-group my-3">
                    <x-forms.label fieldId="description-text" :fieldLabel="__('app.description')">
                    </x-forms.label>
                    <textarea name="description" id="description-text" rows="4" class="form-control">{{ $hasProduct ? $product->description : '' }}</textarea>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 product-description-attributes @if ($hideDescriptionAttributes) d-none @endif">
                <x-forms.text fieldId="specification" :fieldLabel="__('app.specification')" fieldName="specification" :fieldPlaceholder="__('app.specification')" :fieldValue="$hasProduct ? $product->specification ?? '' : ''">
                </x-forms.text>
            </div>
            <div class="col-lg-3 col-md-6 product-description-attributes @if ($hideDescriptionAttributes) d-none @endif">
                <x-forms.text fieldId="product_source" :fieldLabel="__('app.productSource')" fieldName="product_source" :fieldPlaceholder="__('app.productSource')" :fieldValue="$hasProduct ? $product->product_source ?? '' : ''">
                </x-forms.text>
            </div>
            <div class="col-lg-3 col-md-6 product-description-attributes @if ($hideDescriptionAttributes) d-none @endif">
                <x-forms.text fieldId="brand" :fieldLabel="__('app.brand')" fieldName="brand" :fieldPlaceholder="__('app.brand')" :fieldValue="$hasProduct ? $product->brand ?? '' : ''">
                </x-forms.text>
            </div>
            <div class="col-lg-3 col-md-6 product-description-attributes @if ($hideDescriptionAttributes) d-none @endif">
                <x-forms.text fieldId="product_grade" :fieldLabel="__('app.productGrade')" fieldName="product_grade" :fieldPlaceholder="__('app.productGrade')" :fieldValue="$hasProduct ? $product->product_grade ?? '' : ''">
                </x-forms.text>
            </div>
        </div>
    </div>
</div>
